export const TodosConsts = {
    LONG_FETCH_SUCCESS: 'LONG_FETCH_SUCCESS',
    LONG_FETCH_FAILED: 'LONG_FETCH_FAILED',

    LONG_POST_SUCCESS: 'LONG_POST_SUCCESS',
    LONG_POST_FAILED: 'LONG_POST_FAILED',

    LONG_UPDATE_SUCCESS: 'LONG_UPDATE_SUCCESS',
    LONG_UPDATE_FAILED: 'LONG_UPDATE_FAILED'
}

export const rootURL = 'https://boiling-sands-54275.herokuapp.com'
