export const TodosConsts = {
    LONG_FETCH_SUCCESS: 'LONG_FETCH_SUCCESS',
    LONG_FETCH_FAILED: 'LONG_FETCH_FAILED',
    LONG_UPDATE_SUCCESS: 'LONG_UPDATE_SUCCESS',
    LONG_UPDATE_FAILED: 'LONG_UPDATE_FAILED'
}

export const rootURL = 'http://localhost:8080'
